name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  modal_progress_hud: ^0.1.3
  cloud_firestore: ^3.1.17
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
